In [1]:
import torch

In [2]:
torch.rand(2,2)

tensor([[0.9061, 0.5037],
        [0.0956, 0.2355]])

In [3]:
x=torch.empty(4)
print(x)  #1d tensor

tensor([1.0812e+10, 3.1957e-41, 1.0813e+10, 3.1957e-41])


In [4]:
#above we get 4 values of uninitialized data.

In [5]:
x=torch.empty(2,3)
print(x)   #2d tensor

tensor([[1.0849e+10, 3.1957e-41, 1.0798e+10],
        [3.1957e-41, 8.9683e-44, 0.0000e+00]])


In [6]:
#3d tensor
torch.empty(2,2,3)

tensor([[[1.0439e+10, 3.1957e-41, 1.0439e+10],
         [3.1957e-41, 1.9856e+29, 1.7411e+25]],

        [[5.5115e-11, 1.3556e-19, 1.3563e-19],
         [1.6886e+31, 3.2600e-12, 2.0194e-19]]])

In [7]:
torch.empty(3,2,2,4)  #4d tensor

tensor([[[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00, -3.4628e+10,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00, -9.3378e+10,  4.4095e-41]]],


        [[[ 1.0327e+10,  3.1957e-41, -0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  2.2421e-44,  0.0000e+00,  0.0000e+00]],

         [[-5.0645e+10,  4.4095e-41, -9.3338e+10,  4.4095e-41],
          [-1.5024e+11,  4.4095e-41, -9.5410e-08,  4.4096e-41]]]])

In [8]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [9]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [10]:
x=torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [11]:
x.size()

torch.Size([2, 2])

In [12]:
x.ndim

2

In [13]:
x=torch.ones(3,3,dtype=torch.int)
print(x)  #specified datatype

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [14]:
torch.tensor([4,2,3,1,5,2])

tensor([4, 2, 3, 1, 5, 2])

In [16]:
#ensuring we get unique random values everytime
torch.manual_seed(42)
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])


In [17]:
z=x+y
print(z)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])


In [18]:
torch.add(x,y)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])

In [19]:
torch.sub(x,y)

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])

In [20]:
torch.mul(x,y)

tensor([[0.3445, 0.5498],
        [0.0982, 0.7613]])

In [21]:
torch.div(x,y)

tensor([[2.2596, 1.5227],
        [1.4922, 1.2087]])

In [22]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.9408, 0.1332],
        [0.9346, 0.5936]])
tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])


In [23]:
#inplace addition
y.add_(x)

tensor([[1.8102, 0.7009],
        [1.6757, 1.0230]])

In [25]:
#y is replaced by addition of x and y.
z=x+y
print(z)

tensor([[2.7509, 0.8341],
        [2.6103, 1.6166]])


In [27]:
x=torch.rand(5,3)

In [28]:
x

tensor([[0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814]])

In [29]:
x[:,0]   #1st column

tensor([0.0753, 0.3376, 0.9040, 0.6343, 0.9464])

In [30]:
x[:,1]

tensor([0.8860, 0.8090, 0.5547, 0.3644, 0.7890])

In [32]:
x=torch.rand(1)
x

tensor([0.7886])

In [33]:
x.item() #gives exact value of only 1 tensor

0.788632333278656

In [34]:
x=torch.rand(4,4)
print(x)

tensor([[0.5895, 0.7539, 0.1952, 0.0050],
        [0.3068, 0.1165, 0.9103, 0.6440],
        [0.7071, 0.6581, 0.4913, 0.8913],
        [0.1447, 0.5315, 0.1587, 0.6542]])


In [35]:
x.view(16)
#in just 1d tensor we get 16 values.

tensor([0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071,
        0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542])

In [36]:
#in the form of 3d tensor
x.view(2,2,4)

tensor([[[0.5895, 0.7539, 0.1952, 0.0050],
         [0.3068, 0.1165, 0.9103, 0.6440]],

        [[0.7071, 0.6581, 0.4913, 0.8913],
         [0.1447, 0.5315, 0.1587, 0.6542]]])

In [37]:
#converting tensor to numpy
torch.ones(6)

tensor([1., 1., 1., 1., 1., 1.])

In [38]:
a=torch.ones(6)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [39]:
b=a.numpy() #converting tensor to numpy

In [40]:
print(b)
print(type(b))

[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [41]:
a.add_(3)

tensor([4., 4., 4., 4., 4., 4.])

In [42]:
print(a)

tensor([4., 4., 4., 4., 4., 4.])


In [43]:
print(b)

[4. 4. 4. 4. 4. 4.]


In [44]:
#numpy array is also changed as both point to same memory location of CPU.
#so inplace operation on a changes b also.

In [46]:
#converting numpy array to tensor
import numpy as np
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [47]:
b=torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [48]:
a+=2
print(a)

[3. 3. 3. 3. 3.]


In [49]:
print(b)

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [50]:
#tensor is also changed as both point to same location in CPU.

In [53]:
#Backpropagation In Pytorch --> to calculate derivatives
x=torch.tensor(4.,requires_grad=True)
print(x)
#input must be a floating point.

tensor(4., requires_grad=True)


In [54]:
y=x**3
print(y)

tensor(64., grad_fn=<PowBackward0>)


In [55]:
#dy/dx=3x**2

In [56]:
y.backward()

In [57]:
print(x.grad)

tensor(48.)


In [58]:
#above we calculated derivative for x=4 in y.

In [59]:
l1=[[2.,3.,5.],[6.,9.,11.],[13.,17.,18.]]
x=torch.tensor(l1,requires_grad=True)
print(x)

tensor([[ 2.,  3.,  5.],
        [ 6.,  9., 11.],
        [13., 17., 18.]], requires_grad=True)


In [60]:
#y=x**3+x**2
#dy/dx=3x**2+2x
y=x**3+x**2
print(y)

tensor([[  12.,   36.,  150.],
        [ 252.,  810., 1452.],
        [2366., 5202., 6156.]], grad_fn=<AddBackward0>)


In [61]:
#y.backward() gives error as gradient gives scalar outputs.
#so we do the following steps.
z=y.sum()

In [62]:
print(z)

tensor(16436., grad_fn=<SumBackward0>)


In [63]:
z.backward()

In [64]:
print(x.grad)

tensor([[  16.,   33.,   85.],
        [ 120.,  261.,  385.],
        [ 533.,  901., 1008.]])


In [65]:
#we get derivative or gradient at diff values of x.